version: '3.8'

services:
  princess-selene-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_TOKEN=${API_TOKEN}
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      - bot_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*bot.py"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_logs:
    driver: local