version: '3.8'

services:
  princess-selene-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_TOKEN=${API_TOKEN}
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - PORT=8000
    volumes:
      - bot_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_logs:
    driver: local