services:
  - type: background-worker
    name: princess-selene-bot
    runtime: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO.git
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_BASE_URL
        sync: false
      - key: API_TOKEN
        sync: false  
      - key: BOT_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"